@extends('layout.index')
@section('title', 'Política de Privacidade')
@section('content')
<div class="container bg-border" style="margin-top:120px">
    <div class="bg-headline">
        <span>Política de Privacidade</span>
    </div>
    <div class="bg-content">
        <div class="container">
            <div class="bg-title">{{ htmlspecialchars(config('otserver.site.serverName')) }} Política de Privacidade</div>
            <div id="rules" class="main-content">
                <p>O {{ config('otserver.server.serverName') }}, respeita os direitos de privacidade de todos os usuários e está ciente da importância de proteger os dados pessoais armazenados. Medidas organizacionais e técnicas substanciais foram tomadas para garantir a segurança de todos os dados pessoais que são coletados. Esta política de privacidade explica em detalhes quais informações são coletadas e para quais fins elas podem ser processadas e usadas.</p>
                <ul>
                    <li>O {{ config('otserver.server.serverName') }} coleta, processa e usa dados pessoais para a conclusão e execução de um contrato de serviço do usuário com O {{ config('otserver.server.serverName') }}. Os dados pessoais incluem dados de estoque, como nome, endereço e data de nascimento de um usuário, bem como dados de uso, como número de conta, senha e endereço IP.</li>
                    <li>O {{ config('otserver.server.serverName') }} coleta os dados de uso que são automaticamente determinados e transmitidos por navegadores da web ou qualquer outro software cliente sempre que os sites do {{ config('otserver.server.serverName') }} ({{ config('app.url') }}) ou um dos outros serviços online do {{ config('otserver.server.serverName') }} são usados. Esses dados de uso incluem, mas não se limitam a, endereço IP, versão do navegador, tempo de acesso, informações sobre o tipo e o objetivo das solicitações e dados sobre hardware e software do sistema de computador do usuário. Ele é salvo em arquivos de protocolo, com algumas das informações sendo armazenadas de forma anônima. Entre outras finalidades, esses dados são usados pela {{ config('otserver.server.serverName') }} para a compilação de pesquisas estatísticas anônimas sobre o uso de seus serviços online e para a análise de erros e a otimização de seus serviços.</li>
                    <li>O {{ config('otserver.server.serverName') }} usa, entre outras coisas, cookies para coletar, processar e usar dados de uso a fim de permitir, por exemplo, o gerenciamento de contas e de configurações pessoais, a participação no fórum de discussão e o uso de outros serviços personalizados.</li>
                    <li>O {{ config('otserver.server.serverName') }} coleta, processa e usa dados de estoque e uso, na medida do necessário em casos individuais, se for necessário para revelar e impedir o comportamento fraudulento ou qualquer outra forma de uso dos serviços do {{ config('otserver.server.serverName') }} que viole os regulamentos legais ou o contrato de serviço. Em particular, O {{ config('otserver.server.serverName') }} reserva-se o direito de registrar, processar e usar informações como o tempo e o conteúdo das conversas e expressões de opinião que ocorrem em seus serviços online se houver reclamações, relatórios ou outras indicações confiáveis de comportamento que violam os regulamentos legais ou o contrato de serviço, por exemplo, o insulto sério de outros usuários. Este regulamento se estende a todas as partes do serviço online do {{ config('otserver.server.serverName') }}, incluindo, mas não se limitando a, canais de guild, canais privados e mensagens privadas.</li>
                    <li>O {{ config('otserver.server.serverName') }} coleta, processa e usa dados pessoais em conexão com reclamações e solicitações ao seu suporte ao usuário, a fim de atender às solicitações da maneira mais eficiente e satisfatória possível. Os dados coletados para tais fins incluem, mas não se limitam a, o endereço de e-mail, a data do contato e seu conteúdo. Além disso, O {{ config('otserver.server.serverName') }} processa e usa esses dados para compilar pesquisas estatísticas anônimas para a otimização do atendimento ao cliente.</li>
                    <li>O {{ config('otserver.server.serverName') }} coleta, processa e usa dados pessoais com a finalidade de realizar ações de marketing, como o envio de e-mails que contenham informações gerais ou conteúdo promocional, desde que o usuário concorde em receber esses e-mails separadamente durante o processo de criação da conta ou em qualquer momento posterior por selecionando a opção "Newsletter" na página da conta. Cada usuário pode cancelar o recebimento desse tipo de informação a qualquer momento. Isso pode ser feito desmarcando a opção de conta mencionada "Boletim informativo" ou clicando diretamente no link cancelar inscrição em qualquer boletim informativo recebido. Além disso, O {{ config('otserver.server.serverName') }} processa e usa dados pessoais para compilar pesquisas estatísticas anônimas com o propósito de melhorar sua gama de serviços.</li>
                    <li>O {{ config('otserver.server.serverName') }} exibe os nomes dos personagens para todos os visitantes em todos os sites do {{ config('otserver.server.serverName') }}, bem como para todos os usuários em seus serviços online em conexão com certas atividades de jogo de um usuário, a fim de permitir que outros usuários contatem seletivamente este usuário. Isso ocorre, por exemplo, quando o usuário usa personagens online, quando eles atuam como parte de associações de personagens ou, possivelmente, quando são registrados em listas de recordes. Além disso, O {{ config('otserver.server.serverName') }} geralmente torna os dados de uso de personagens, por exemplo, o tempo de seu uso mais recente ou informações sobre sua morte, disponíveis para todos os visitantes em todos os sites do {{ config('otserver.server.serverName') }}, bem como para todos os usuários nos serviços online do {{ config('otserver.server.serverName') }}. O {{ config('otserver.server.serverName') }} disponibiliza informações, como o registro de violações de regras ou a lista de personagens derrotados, para alguns outros usuários, que têm uma função de supervisão entre a comunidade de usuários.</li>
                    <li>
                        <span>Na medida em que a transferência de dados para terceiros não seja explicitamente permitida por lei, O {{ config('otserver.server.serverName') }}</span>
                        <ul>
                            <li>Transmite os dados pessoais, na medida do necessário, às autoridades de aplicação da lei e de supervisão com o objetivo de prevenir perigos para a segurança nacional ou pública, bem como para o julgamento de infrações penais.</li>
                            <li>repassa o nome, endereço e, na medida do necessário em casos individuais, outros dados pessoais dos usuários às empresas parceiras, por exemplo, para fins de tratamento de transações de pagamento ou para fornecer outros serviços no âmbito do serviço de usuários acordo com O {{ config('otserver.server.serverName') }}.</li>
                        </ul>
                        <span>Terceiros podem estar localizados em países fora da União Européia, mas eles são obrigados a proteger os dados pessoais da mesma forma que O {{ config('otserver.server.serverName') }}. O {{ config('otserver.server.serverName') }} não irá, além dos casos acima mencionados, passar dados pessoais a terceiros, e somente os funcionários do {{ config('otserver.server.serverName') }} terão acesso aos dados pessoais para cumprir as tarefas especificadas acima.</span>
                    </li>
                    <li>O {{ config('otserver.server.serverName') }} pode mudar esta política de privacidade a qualquer momento. O {{ config('otserver.server.serverName') }} notificará todos os usuários sobre as mudanças colocando um aviso em destaque no site do Tibia. A política de privacidade alterada entrará em vigor 30 dias após seu anúncio oficial. Ela se aplicará totalmente a qualquer usuário que não tenha revogado sua declaração de consentimento dentro deste período de tempo. Todos os usuários são obrigados a revisar esta política em intervalos regulares para se manterem informados sobre quaisquer alterações.</li>
                    <li>Os usuários têm o direito de acesso aos seus dados pessoais processados pelo {{ config('otserver.server.serverName') }} (Art. 15 GDPR), bem como o direito de retificar (Art. 16 GDPR) ou apagar (Art. 17 GDPR) esses dados pessoais. Além disso, eles têm o direito de restrição de processamento (Art. 18 GDPR), o direito de se opor ao tratamento de dados pessoais (Art. 21 GDPR) e o direito de portabilidade de dados (Art. 20 DSGVO). Os usuários podem exercer esses direitos enviando um e-mail para {{ config('otserver.server.ownerEmail') }}. Se os usuários revogarem sua declaração de consentimento para o processamento de seus dados pessoais, suas contas no {{ config('otserver.server.serverName') }} serão bloqueadas e os serviços personalizados do {{ config('otserver.server.serverName') }} não estarão mais disponíveis através dessas contas.</li>
                    <li>Os usuários que tiverem perguntas sobre esta política de privacidade ou sobre o processamento de seus dados pessoais também podem entrar em contato com o diretor de proteção de dados do {{ config('otserver.server.serverName') }}, Caso o responsável pela proteção de dados não possa responder ao pedido de forma satisfatória, os utilizadores têm a possibilidade de apresentar uma reclamação junto da autoridade de supervisão responsável pelo seu estado ou país.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection
